version: "3"
services:
  postgresql:
    image: postgres:11.19-alpine
    container_name: postgresql11
    volumes:
      - "${POSTGRES_DATA}:/var/lib/postgresql/data"
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "5435:5432"
    restart: unless-stopped
