version: "3"
services:
  postgresql:
    image: postgres:11
    container_name: postgresql11
    volumes:
      - "${POSTGRES_DATA}:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "5433:5432"
    restart: always
