version: "3"
services:
  postgresql:
    image: postgres:15
    container_name: postgresql15
    volumes:
      - "${POSTGRES_DATA}:/var/lib/postgresql/data"
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_POTRT:-5432}:5432"
    restart: unless-stopped
