services:
  postgresql:
    image: postgres:13
    container_name: postgresql13
    volumes:
      - "${POSTGRES_DATA}:/var/lib/postgresql/data"
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
    ports:
      - "54313:5432"
    restart: unless-stopped
